# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0af603ab0b79c8b537aa541c1b66b366cf9715271f57c61cbdc219ef27551fbc496805d57a8715111670f6aa9c65fab8d0e059930df02b15a9644d3596549f0b

test:
  secret_key_base: bc20abcedbaf054e0d6ac2e73c305dfde77c79d8bb48d52977ac785d284361e3f26a44e70bb75ba7b370de089af8c0c841d23063154fdcf738e5927cb5b4ba05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
